
name: No_packagelock_Build_master-new

on:
  workflow_dispatch:
  #watch:
  #  types: started
  repository_dispatch:
    types: relase_build
    
jobs:
  iot2050_debian-example-image:
    name: example image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Free Disk Space
        uses: ./.github/workflows/free-disk-space
      - name: Build image
        run: git fetch && git pull origin master && ./kas-container build kas-iot2050-example.yml 
      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: iot2050-example-image
          path: |
            build/tmp/deploy/images/iot2050/iot2050-image-example-iot2050-debian-iot2050.wic
            build/tmp/work/iot2050-debian-arm64/iot2050-firmware-update/0.2-r0/iot2050-firmware-update_0.2_arm64.deb
            build/tmp/work/iot2050-debian-arm64/u-boot-iot2050-pg2/2022.01-r0/u-boot-2022.01/u-boot-initial-env

  iot2050_debian-rt-example-image:
    name: RT example image packge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Free Disk Space
        uses: ./.github/workflows/free-disk-space
      - name: Build RT image
        run: git fetch && git pull origin master && ./kas-container build kas-iot2050-example.yml:kas/opt/preempt-rt.yml 
      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: iot2050-example-image-rt
          path: build/tmp/deploy/images/iot2050/iot2050-image-example-iot2050-debian-iot2050.wic
          
  iot2050-sdk:
    name: SDK packge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Free Disk Space
        uses: ./.github/workflows/free-disk-space
      - name: Build SDK
        run: git fetch && git pull origin master && ./kas-container build kas-iot2050-example.yml:kas/opt/sdk.yml 
      - name: Archive sdk
        uses: actions/upload-artifact@v3
        with:
          name: iot2050-sdk
          path: build/tmp/deploy/images/iot2050/*.tar*
          
  iot2050_bootloaders:
    name: Bootloaders packge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Free Disk Space
        uses: ./.github/workflows/free-disk-space
      - name: Build bootloader image for PG1
        run: git fetch && git pull origin master && ./kas-container build kas-iot2050-boot-pg1.yml 
      - name: Build bootloader image for PG2
        run: ./kas-container build kas-iot2050-boot-pg2.yml 
      - name: Archive bootloaders
        uses: actions/upload-artifact@v3
        with:
          name: iot2050-bootloaders
          path: build/tmp/deploy/images/iot2050/*.bin
